language: java
jdk: oraclejdk8
script: 
- ant run
- ant jar
before_deploy:
# Set up git user name and tag this commit
- git config --local user.name DKaito
- git config --local user.email bartlomiej.chmielarz@gmail.com
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
 provider: releases
 api_key: $GH_TOKEN
 file: /home/travis/build/IIS-ZPI/ZPI_2018_Dzienni_3/build/out/TaxCalculator.jar
 skip_cleanup: true
 file_glob: true
 on:
  repo: IIS-ZPI/ZPI_2018_Dzienni_3
  branch: master